#!/usr/bin/env bash

scss='sass --sourcemap=none'

$scss example/flexbox.scss example/flexbox.css
$scss example/index.scss example/index.css
$scss example/shape.scss example/shape.css
$scss example/grid.scss example/grid.css

$scss gist/progress.scss gist/progress.css
$scss gist/loading.scss gist/loading.css
$scss gist/slide.scss gist/slide.css
$scss gist/popup.scss gist/popup.css
